name: task_manager
description: "Task manager project"
publish_to: 'none'

version: 1.0.0+1
environment:
  sdk: ^3.5.0
dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_svg: ^2.0.10+1
  pinput: ^5.0.0
  get: ^4.6.6
  flutter_secure_storage: ^9.2.2
  another_flushbar: ^1.12.30

  # Firebase pakeges
  firebase_core: ^3.8.0
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  
  logger: ^2.5.0

  image_picker: ^1.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/images/