// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAFCGdSzeb268_uXErFyoMWx_D2fO6ts0',
    appId: '1:967074109919:android:49821641dbb6b5a5d7cc6a',
    messagingSenderId: '967074109919',
    projectId: 'task-manager-e832d',
    storageBucket: 'task-manager-e832d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBVw7y1PpjJSPFDkkub9IXpkbTDgewHUw',
    appId: '1:967074109919:ios:d81dc538761a4024d7cc6a',
    messagingSenderId: '967074109919',
    projectId: 'task-manager-e832d',
    storageBucket: 'task-manager-e832d.firebasestorage.app',
    iosBundleId: 'com.tamimsoft.taskmanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBVw7y1PpjJSPFDkkub9IXpkbTDgewHUw',
    appId: '1:967074109919:ios:d81dc538761a4024d7cc6a',
    messagingSenderId: '967074109919',
    projectId: 'task-manager-e832d',
    storageBucket: 'task-manager-e832d.firebasestorage.app',
    iosBundleId: 'com.tamimsoft.taskmanager',
  );

}